version: "3.9"
services:
  wordtrack_app:
    restart: always
    build:
      context: .
    volumes:
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
    networks:
      - nginx-network
    environment:
      - HOST_NAME="https://wordtrack.elisei.nl/"

networks:
  nginx-network:
    external: true
    name: nginx-network
