version: "3.9"
services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - ./data:/app/data
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network