# Generated by Django 4.2.5 on 2023-10-12 17:40

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnedCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("native", models.TextField()),
                ("foreign", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "New"), ("LEARN", "Learning"), ("REPEAT", "Repeat"), ("DELETE", "Delete")],
                        default="NEW",
                        max_length=6,
                    ),
                ),
                ("group", models.TextField()),
                ("learning_stage", models.IntegerField(default=0)),
                ("repeat_on", models.DateField(default=datetime.datetime.now)),
                ("last_repeated", models.DateField(default=datetime.datetime.now)),
                ("repetition_period", models.IntegerField(default=0)),
                (
                    "next_repetition_direction",
                    models.CharField(
                        choices=[("TO_NATIVE", "To Native"), ("TO_FOREIGN", "To Foreign")],
                        default="TO_FOREIGN",
                        max_length=14,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
