# Generated by Django 4.2.6 on 2023-10-25 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_alter_word_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("user", "native", "foreign")},
        ),
    ]
